apiVersion: v1
kind: Service
metadata: 
  name: mongos
  namespace: sharding
spec: 
  selector: 
    app: mongos
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
   