apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sharding
  name: mongos-deployment
  labels:
    mongoDB-sharding: "true"
    mongoDB-secured: "true"
  annotations: 
    author: JMCF
spec:
  selector: 
    matchLabels:
      app: mongos
  replicas: 3
  template:
    metadata: 
      labels: 
        app: mongos
    spec: 
      terminationGracePeriodSeconds: 10
      volumes: 
        - name: initial-secret-volume
          secret:
            secretName: mongo-secret-mongos
        - name: secret-volume
          emptyDir: {}
      initContainers:
        - name: set-file-permissions
          image: busybox
          command:
            - sh
            - -c
          args:
            - >- 
                 cp /var/init-secrets/tls.keycert /var/secrets/tls.keycert && 
                 chmod 400 /var/secrets/tls.keycert &&
                 chown 999:999 /var/secrets/tls.keycert;
                 cp /var/init-secrets/tls.cluster.keycert /var/secrets/tls.cluster.keycert && 
                 chmod 400 /var/secrets/tls.cluster.keycert &&
                 chown 999:999 /var/secrets/tls.cluster.keycert;
          volumeMounts:
            - mountPath: /var/init-secrets
              name: initial-secret-volume
              readOnly: true
            - mountPath: /var/secrets
              name: secret-volume
              readOnly: false
      containers: 
        - name: mongo-db
          image: mongo:4.2.6
          ports: 
            - containerPort: 27017
              protocol: TCP
          volumeMounts: 
            - mountPath: /var/secrets
              name: secret-volume
              readOnly: true
          command:
            - mongos         
          args:
            - --verbose
            - --bind_ip_all
            - --tlsMode
            - requireTLS
            - --clusterAuthMode 
            - x509
            - --tlsClusterFile
            - /var/secrets/tls.cluster.keycert
            - --tlsCertificateKeyFile
            - /var/secrets/tls.keycert
            - --tlsCAFile
            - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - --configdb
            - replica-blog-config-server/mongo-db-statefulset-config-server-0.mongo-db-replica-config-server.sharding.svc.cluster.local:27019,mongo-db-statefulset-config-server-1.mongo-db-replica-config-server.sharding.svc.cluster.local:27019,mongo-db-statefulset-config-server-2.mongo-db-replica-config-server.sharding.svc.cluster.local:27019
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
